# Write your MySQL query statement below
SELECT p.PRODUCT_NAME AS product_name,SUM(o.UNIT) AS unit
FROM PRODUCTS p LEFT JOIN ORDERS o 
ON p.PRODUCT_ID=o.PRODUCT_ID 
AND o.ORDER_DATE>='2020-02-01'
AND ORDER_DATE<'2020-03-01'

GROUP BY p.PRODUCT_ID HAVING SUM(o.UNIT)>=100 ;