# Write your MySQL query statement below
#SELECT DISTINCT USER_ID,COUNT(FOLLOWER_ID) GROUP BY USER ID;
SELECT USER_ID,COUNT(FOLLOWER_ID) AS FOLLOWERS_COUNT FROM FOLLOWERS GROUP BY USER_ID ORDER BY USER_ID ;